"""add_priority_subtasks_sections_sync_metadata

Revision ID: 4d4afd73e72a
Revises: d1e2f3a4b5c6
Create Date: 2026-03-25 23:23:52.376397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d4afd73e72a'
down_revision: Union[str, Sequence[str], None] = 'd1e2f3a4b5c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('list_id', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('external_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['list_id'], ['lists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sections_id'), 'sections', ['id'], unique=False)
    op.add_column('calendar_integrations', sa.Column('reminders_status', sa.Enum('ACTIVE', 'ERROR', 'SYNCING', 'DISCONNECTED', name='integrationstatus'), nullable=True))
    op.add_column('calendar_integrations', sa.Column('reminders_last_error', sa.String(), nullable=True))
    op.add_column('calendar_integrations', sa.Column('reminders_last_sync_at', sa.DateTime(), nullable=True))
    op.add_column('calendars', sa.Column('is_todo', sa.Boolean(), nullable=True))
    op.add_column('lists', sa.Column('external_id', sa.String(), nullable=True))
    op.add_column('lists', sa.Column('calendar_integration_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'lists', 'calendar_integrations', ['calendar_integration_id'], ['id'], ondelete='SET NULL')
    # Add priority with server_default=0 so existing rows get a value
    op.add_column('tasks', sa.Column('priority', sa.Integer(), server_default='0', nullable=False))
    # Data migration: important=True → priority=1
    op.execute("UPDATE tasks SET priority = 1 WHERE important = true")
    op.add_column('tasks', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('section_id', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False))
    op.add_column('tasks', sa.Column('completed_at', sa.DateTime(), nullable=True))
    op.add_column('tasks', sa.Column('external_id', sa.String(), nullable=True))
    op.add_column('tasks', sa.Column('etag', sa.String(), nullable=True))
    op.add_column('tasks', sa.Column('last_modified_remote', sa.DateTime(), nullable=True))
    op.add_column('tasks', sa.Column('sync_status', sa.String(), nullable=True))
    op.add_column('tasks', sa.Column('calendar_integration_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_tasks_section_id'), 'tasks', ['section_id'], unique=False)
    op.create_unique_constraint('uq_task_external_integration', 'tasks', ['external_id', 'calendar_integration_id'])
    op.create_foreign_key(None, 'tasks', 'calendar_integrations', ['calendar_integration_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'tasks', 'sections', ['section_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'tasks', 'tasks', ['parent_id'], ['id'], ondelete='SET NULL')
    op.drop_column('tasks', 'important')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('important', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    # Data migration: priority=1 → important=True
    op.execute("UPDATE tasks SET important = true WHERE priority = 1")
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint('uq_task_external_integration', 'tasks', type_='unique')
    op.drop_index(op.f('ix_tasks_section_id'), table_name='tasks')
    op.drop_column('tasks', 'calendar_integration_id')
    op.drop_column('tasks', 'sync_status')
    op.drop_column('tasks', 'last_modified_remote')
    op.drop_column('tasks', 'etag')
    op.drop_column('tasks', 'external_id')
    op.drop_column('tasks', 'completed_at')
    op.drop_column('tasks', 'sort_order')
    op.drop_column('tasks', 'section_id')
    op.drop_column('tasks', 'parent_id')
    op.drop_column('tasks', 'priority')
    op.drop_constraint(None, 'lists', type_='foreignkey')
    op.drop_column('lists', 'calendar_integration_id')
    op.drop_column('lists', 'external_id')
    op.drop_column('calendars', 'is_todo')
    op.drop_column('calendar_integrations', 'reminders_last_sync_at')
    op.drop_column('calendar_integrations', 'reminders_last_error')
    op.drop_column('calendar_integrations', 'reminders_status')
    op.drop_index(op.f('ix_sections_id'), table_name='sections')
    op.drop_table('sections')
    # ### end Alembic commands ###
