"""add_photo_and_icon_fields

Revision ID: 5500b4fc0d01
Revises: e20c4aa609e6
Create Date: 2026-01-30 05:04:25.155371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5500b4fc0d01'
down_revision: Union[str, Sequence[str], None] = 'e20c4aa609e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('family_members', sa.Column('photo_url', sa.String(), nullable=True))
    op.alter_column('family_members', 'is_system',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.add_column('responsibilities', sa.Column('icon_url', sa.String(), nullable=True))
    op.add_column('responsibilities', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('responsibilities', 'description')
    op.drop_column('responsibilities', 'icon_url')
    op.alter_column('family_members', 'is_system',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_column('family_members', 'photo_url')
    # ### end Alembic commands ###
