"""add family_members and responsibilities + update todo

Revision ID: 7747b0506845
Revises: 5ca77c4c04ff
Create Date: 2026-01-23 22:43:18.460582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '7747b0506845'
down_revision: Union[str, Sequence[str], None] = '5ca77c4c04ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('family_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_family_members_first_name'), 'family_members', ['first_name'], unique=False)
    op.create_index(op.f('ix_family_members_id'), 'family_members', ['id'], unique=False)
    op.create_index(op.f('ix_family_members_last_name'), 'family_members', ['last_name'], unique=False)
    op.create_table('responsibilities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('assigned_to', postgresql.ENUM('WILL', 'CELINE', 'ALL', name='assignedto', create_type=False), nullable=False),
    sa.Column('important', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_responsibilities_id'), 'responsibilities', ['id'], unique=False)
    op.create_index(op.f('ix_responsibilities_name'), 'responsibilities', ['name'], unique=False)
    op.alter_column('todos', 'important',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todos', 'important',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('ix_responsibilities_name'), table_name='responsibilities')
    op.drop_index(op.f('ix_responsibilities_id'), table_name='responsibilities')
    op.drop_table('responsibilities')
    op.drop_index(op.f('ix_family_members_last_name'), table_name='family_members')
    op.drop_index(op.f('ix_family_members_id'), table_name='family_members')
    op.drop_index(op.f('ix_family_members_first_name'), table_name='family_members')
    op.drop_table('family_members')
    # Note: Not dropping 'assignedto' enum type as it's managed by migration 5ca77c4c04ff
    # ### end Alembic commands ###
