"""add_color_to_family_members

Revision ID: 9f725bf2eef2
Revises: 7c14f1caab65
Create Date: 2026-02-07 23:07:01.442005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f725bf2eef2'
down_revision: Union[str, Sequence[str], None] = '7c14f1caab65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('family_members', sa.Column('color', sa.String(), nullable=True))
    # ### end Alembic commands ###

    # Auto-assign colors to existing members
    DEFAULT_COLORS = [
        "#3B82F6",  # blue
        "#EF4444",  # red
        "#10B981",  # green
        "#8B5CF6",  # purple
        "#F97316",  # orange
        "#14B8A6",  # teal
        "#EC4899",  # pink
        "#6366F1",  # indigo
    ]

    conn = op.get_bind()
    members = conn.execute(
        sa.text("SELECT id FROM family_members WHERE is_system = false ORDER BY id")
    ).fetchall()
    for i, member in enumerate(members):
        color = DEFAULT_COLORS[i % len(DEFAULT_COLORS)]
        conn.execute(
            sa.text("UPDATE family_members SET color = :color WHERE id = :id"),
            {"color": color, "id": member[0]},
        )

    # Set terracotta for system "Everyone" member
    conn.execute(
        sa.text("UPDATE family_members SET color = :color WHERE is_system = true"),
        {"color": "#D97452"},
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('family_members', 'color')
    # ### end Alembic commands ###
