"""add_calendar_integration_table_and_sync_columns

Revision ID: c780d2eaccde
Revises: c8f3a1b2d4e5
Create Date: 2026-02-10 22:03:16.426310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c780d2eaccde'
down_revision: Union[str, Sequence[str], None] = 'c8f3a1b2d4e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calendar_integrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('family_member_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('encrypted_password', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'ERROR', 'SYNCING', 'DISCONNECTED', name='integrationstatus'), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True),
    sa.Column('last_error', sa.String(), nullable=True),
    sa.Column('sync_range_past_days', sa.Integer(), nullable=True),
    sa.Column('sync_range_future_days', sa.Integer(), nullable=True),
    sa.Column('selected_calendars', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['family_member_id'], ['family_members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calendar_integrations_id'), 'calendar_integrations', ['id'], unique=False)
    op.add_column('calendar_events', sa.Column('etag', sa.String(), nullable=True))
    op.add_column('calendar_events', sa.Column('last_modified_remote', sa.DateTime(), nullable=True))
    op.add_column('calendar_events', sa.Column('sync_status', sa.String(), nullable=True))
    op.add_column('calendar_events', sa.Column('calendar_integration_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('calendar_events_external_id_key'), 'calendar_events', type_='unique')
    op.create_unique_constraint('uq_calendar_event_external_integration', 'calendar_events', ['external_id', 'calendar_integration_id'])
    op.create_foreign_key('fk_calendar_events_integration_id', 'calendar_events', 'calendar_integrations', ['calendar_integration_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_calendar_events_integration_id', 'calendar_events', type_='foreignkey')
    op.drop_constraint('uq_calendar_event_external_integration', 'calendar_events', type_='unique')
    op.create_unique_constraint(op.f('calendar_events_external_id_key'), 'calendar_events', ['external_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('calendar_events', 'calendar_integration_id')
    op.drop_column('calendar_events', 'sync_status')
    op.drop_column('calendar_events', 'last_modified_remote')
    op.drop_column('calendar_events', 'etag')
    op.drop_index(op.f('ix_calendar_integrations_id'), table_name='calendar_integrations')
    op.drop_table('calendar_integrations')
    # ### end Alembic commands ###
