"""add_meal_plans_table_and_update_recipes

Revision ID: d4046930b2e2
Revises: a5510f8157a2
Create Date: 2026-02-08 03:16:30.677823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd4046930b2e2'
down_revision: Union[str, Sequence[str], None] = 'a5510f8157a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meal_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('category', sa.Enum('BREAKFAST', 'LUNCH', 'DINNER', name='mealcategory'), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=True),
    sa.Column('custom_meal_name', sa.String(), nullable=True),
    sa.Column('was_cooked', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meal_plans_date'), 'meal_plans', ['date'], unique=False)
    op.create_index(op.f('ix_meal_plans_id'), 'meal_plans', ['id'], unique=False)
    op.add_column('recipes', sa.Column('description', sa.String(), nullable=True))
    op.add_column('recipes', sa.Column('cook_time_minutes', sa.Integer(), nullable=True))
    op.add_column('recipes', sa.Column('servings', sa.Integer(), nullable=True))
    op.add_column('recipes', sa.Column('image_url', sa.String(), nullable=True))
    op.add_column('recipes', sa.Column('is_favorite', sa.Boolean(), nullable=True))
    op.add_column('recipes', sa.Column('tags', sa.JSON(), nullable=True))
    op.add_column('recipes', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('recipes', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('recipes', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('recipes', 'ingredients',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               type_=sa.JSON(),
               existing_nullable=True,
               postgresql_using='to_json(ingredients)')
    op.alter_column('recipes', 'instructions',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('recipes', 'instructions',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               nullable=True)
    op.alter_column('recipes', 'ingredients',
               existing_type=sa.JSON(),
               type_=postgresql.ARRAY(sa.VARCHAR()),
               existing_nullable=True)
    op.alter_column('recipes', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('recipes', 'updated_at')
    op.drop_column('recipes', 'created_at')
    op.drop_column('recipes', 'tags')
    op.drop_column('recipes', 'is_favorite')
    op.drop_column('recipes', 'image_url')
    op.drop_column('recipes', 'servings')
    op.drop_column('recipes', 'cook_time_minutes')
    op.drop_column('recipes', 'description')
    op.drop_index(op.f('ix_meal_plans_id'), table_name='meal_plans')
    op.drop_index(op.f('ix_meal_plans_date'), table_name='meal_plans')
    op.drop_table('meal_plans')
    # ### end Alembic commands ###
