"""add responsibilities table

Revision ID: e20c4aa609e6
Revises: ba4ce78a08f8
Create Date: 2026-01-28 21:19:34.243502

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e20c4aa609e6"
down_revision: Union[str, Sequence[str], None] = "ba4ce78a08f8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "responsibilities",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column(
            "category",
            sa.Enum(
                "MORNING",
                "AFTERNOON",
                "EVENING",
                "CHORE",
                name="responsibilitycategory",
            ),
            nullable=False,
        ),
        sa.Column("assigned_to", sa.Integer(), nullable=False),
        sa.Column("frequency", sa.ARRAY(sa.String()), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["assigned_to"],
            ["family_members.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_responsibilities_id"), "responsibilities", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_responsibilities_title"), "responsibilities", ["title"], unique=False
    )
    op.create_table(
        "responsibility_completions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("responsibility_id", sa.Integer(), nullable=False),
        sa.Column("family_member_id", sa.Integer(), nullable=False),
        sa.Column("completion_date", sa.Date(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["family_member_id"],
            ["family_members.id"],
        ),
        sa.ForeignKeyConstraint(
            ["responsibility_id"],
            ["responsibilities.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "responsibility_id",
            "completion_date",
            name="uq_responsibility_completion_date",
        ),
    )
    op.create_index(
        op.f("ix_responsibility_completions_id"),
        "responsibility_completions",
        ["id"],
        unique=False,
    )
    op.alter_column(
        "family_members",
        "is_system",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("false"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "family_members",
        "is_system",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text("false"),
    )
    op.drop_index(
        op.f("ix_responsibility_completions_id"),
        table_name="responsibility_completions",
    )
    op.drop_table("responsibility_completions")
    op.drop_index(op.f("ix_responsibilities_title"), table_name="responsibilities")
    op.drop_index(op.f("ix_responsibilities_id"), table_name="responsibilities")
    op.drop_table("responsibilities")
    sa.Enum(name="responsibilitycategory").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
